readでx, y分割も行うようにした。エラー対応を追加

diff --git a/resize b/resize
--- a/resize
+++ b/resize
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/bash -eu
 
 # Reference documents
 # https://wiki.archlinux.org/title/working_with_the_serial_console
@@ -16,26 +16,31 @@
 # ESC [ 6n ... DSR: Device Status Report: Reports thee cursor position by transmitting "ESC [ width; height R"
 # ESC 8 ... DECRC: DEC Restore Cursor
 
-resize() {
-  [ -t 0 ] || return 1
+function resize() {
+  [ -t 0 ] || { echo "resize: Error: Text terminal is not found" >&2; return 1; }
 
   local oldStty=$(stty -g)
   stty raw -echo min 0
   echo -en '\e7\e[r\e[9999;9999H\e[6n\e8'
 
-  local IFS='[;' _escape geometry
-  read -sd R _escape geometry
-
+  local IFS='[;' _escape y x
+  read -sd R _escape y x
   stty $oldStty
+  ### ここまでを別関数にしようとしたが
+  ### 結果を標準出力からサブシェル経由で受け取るため
+  ### readｈでvt100エスケープシーケンスの読み取りができなくなった。bashのglobal配列なら
 
-  local x=${geometry##*;}; local y=${geometry%%;*}
+  [ -n "$x" ] && [ -n "$y" ] || {
+    echo "resize: Error: Cannot get rows or columns by vt100 escape sequence" >&2
+    return 2
+  }
   echo -n "$TERM $COLUMNS x $LINES"
-  if [ ${COLUMNS} -eq ${x} ] && [ ${LINES} -eq ${y} ]; then
-    echo
-  else
-    echo " -> ${x} x ${y}"
+  if [ ${COLUMNS} -ne ${x} ] || [ ${LINES} -ne ${y} ]; then
+    echo -n " -> ${x} x ${y}"
     stty cols ${x} rows ${y}
   fi
+  echo
 }
 
 resize
+
